Update for 3.1 release
git-svn-id: https://svn.cv.nrao.edu/svn/casa/release/current@13521 ac9c0da5-131f-0410-9009-a9c195f183e6

diff --git a/code/xmlcasa/install/svn_editor b/code/xmlcasa/install/svn_editor
--- a/code/xmlcasa/install/svn_editor
+++ b/code/xmlcasa/install/svn_editor
@@ -3,7 +3,14 @@
 # Inspired by the old setsvneditor.sh, a desire to make it less picky about
 # editors, and 8/25/2006 post by Bart Robinson to users@subversion.tigris.org. 
 
-AIPSROOT=`echo $CASAPATH | awk '{print $1}'`
+casaroot=`echo $CASAPATH | awk '{print $1}'`
+
+svntemplate=$casaroot/code/xmlcasa/install/svntemplate
+
+if [ ! -f $svntemplate ] ; then
+    echo "Could not find ${svntemplate}.  Set CASAPATH."
+    exit 1
+fi
 
 [ $# -eq 1 ] || {
 cat <<EOF
@@ -14,7 +21,7 @@ that inserts the CASA commit log template.
 
 Use: 1. set the environment variable SVN_EDITOR to point to this file.
         (Can also be done by sourcing
-         $AIPSROOT/code/xmlcasa/install/setsvneditor.(c)sh.)
+         $casaroot/code/xmlcasa/install/setsvneditor.(c)sh.)
      2. svn ci
      3. Edit as needed.
      4. "Exit" the editor, i.e. C-x # for emacsclient,
@@ -31,7 +38,7 @@ ed=$VISUAL
 [ -z $ed ] && ed=$EDITOR
 [ -z $ed ] && ed=vi
 
-cat < $AIPSROOT/code/xmlcasa/install/svntemplate > $file.$$
+cat < $svntemplate > $file.$$
 cat $file >> $file.$$
 
 sum=`cksum $file.$$`
