New Development: No             JIRA Issue: Maybe         Ready for Test: Yes      Interface Changes: No What Interface Changed:          Test Programs: Does it print the warning message if java is not found?   Put in Release Notes: Yes              Module(s): tasking            Description: Java is necessary for buildmytasks to run. If java is not found we now print out a message saying you need java and where to get it.
git-svn-id: https://svn.cv.nrao.edu/svn/casa/active@21141 ac9c0da5-131f-0410-9009-a9c195f183e6

diff --git a/gcwrap/install/buildmytasks b/gcwrap/install/buildmytasks
--- a/gcwrap/install/buildmytasks
+++ b/gcwrap/install/buildmytasks
@@ -124,6 +124,14 @@ if [[ ! -e ${SAXONJAR} ]]; then
 fi
 
 [ ! -e "$SAXONJAR" ] && error "can't find the Saxon processor $SAXONJAR!"
+
+which java > /dev/null
+if [ $? -ne 0 ]; then
+   echo "Java was not found in your PATH. Java needs to be available for buildmytasks to work. "
+   echo "Please visit http://www.oracle.com/technetwork/java/javase/downloads/index.html to obtain java."
+   echo "If(Once) java is installed you will need to put java's location in your PATH for buildmytasks to run"
+   exit
+fi
 verbose "Saxon processor: $SAXONJAR"
 SAXON="java -jar $SAXONJAR"
 verbose "Saxon command: $SAXON"
